name: Generate Snake Animation

on:
  schedule: # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # Allows manual execution

  push:
    branches:
      - master # Runs when code is pushed to the master branch

jobs:
  generate:
    permissions:
      contents: write # Grants permission to push the generated file
    runs-on: ubuntu-latest # Specifies the runner environment
    timeout-minutes: 5 # Ensures the job doesn't run indefinitely

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Checks out the repository so the workflow can access files

      - name: Generate snake.svg animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: sumaiyaamin # Uses the repository owner’s username
          outputs: dist/snake.svg?palette=github-dark # Generates the snake animation in dark mode

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output # Pushes the generated file to the 'output' branch
          build_dir: dist # Specifies the directory where the generated file is located
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Uses GitHub’s authentication token for pushing changes
